### PR TITLE
Fix AES and several misimplementations

### PR DESCRIPTION
**Pull request by edqx**

### CODE REVIEW

**Comment by roobscoob** [comment]
is this complete and ready to merge? Or should this be developed on before merging

**Comment by edqx** [comment]
I suggest just merging before you ever work on it. Otherwise I'll just keep making commits. It's a draft either way.

**Comment by roobscoob** [comment]
Merging now! Would like to see some tests on this if possible. Also, would be curious as to why you moved to using version 1.2 instead of the obfuscated version? Were there compatibility

**Comment by edqx** [comment]
There's no better compat, I just personally would keep it as 1.2 rather than being obfuscated — it seems like a net benefit from a programmer point of view; being able to see the DTLS messages in wireshark isn't really a security issue & makes life easier for debugging.

**Comment by edqx** [comment]
I'm not really sure how you'd like me to test the DTLS socket? I'll look into it anyway.

The other tests like the AESGCM class should be fairly straight forward.

**Comment by roobscoob** [comment]
The socket could be tested by writing a test implementation of the abstract Socket class, and using that as the underlying constructor for the DTLS socket.

As for the version, Should we consider exposing a config option for "obfuscated version"? Some countries (i.e. Egypt) block DTLS traffic, and obfuscating the version is the workaround for that.

**Comment by roobscoob** [comment]
honestly a TestSocket class might be good in general. I could definitely see it getting uses in other places. (e.g. as an underlying socket for testing the HazelClient)

**Pull request merged**
